### ISSUE TITLE
Implement data models

### ISSUE THREAD

**Issue by w-gao** [w-gao/toil-wdl#1]
Implement the Python WDL data models in [`twdl/models.py`](https://github.com/w-gao/toil-wdl/blob/main/twdl/models.py). We can then use these models to analyze and validate a WDL workflow without working with the version-specific ANTLR4 (or Hermes) AST nodes. 

## Checklist

- Workflow
  - [X] inputs
  - inner elements
    - declaration
    - [X] call
    - [X] scatter
    - [X] conditional
  - [X] outputs
- Task
  - [X] inputs
  - [X] declarations
  - [x] command
  - [X] runtime
  - [X] outputs
- Struct
  - [ ] ?
- Declaration
  - Types
    - [X] Primitives (String, Int, Float, Boolean, File)
      - [ ] Directory
    - [X] Compound (Array, Pair, Map)
    - [ ] Custom (Struct)
  - Expression
    - [X] Binary operations
    - [X] Unary operations
    - [X] Function call
    - [X] Literal
      - [X] Primitive
        - [X] String (with parts & placeholders)
      - [X] Array, Pair, Map
      - [ ] Struct
    - [X] Identifier
    - [X] Ternary
    - [X] Group
    - [X] Member access
